# Cirrus CI configuration
# https://cirrus-ci.com/github/libexif/exif

freebsd_task:
  name: FreeBSD
  freebsd_instance:
    memory: 1400M
    matrix:
      image_family: freebsd-14-0
      image_family: freebsd-13-2

  env:
    # Set to 10 instead of 1 to avoid problems when new commits are submitted
    # during a run.
    CIRRUS_CLONE_DEPTH: 10
    CFLAGS: -Wall -Wextra -O2
    MAKEFLAGS: -j 3

  pkginstall_script:
    - pkg install -y autoconf automake libtool gettext-tools gettext-runtime popt pkgconf git
    - git clone --depth=1 https://github.com/libexif/libexif.git /tmp/libexif
  builddeps_script:
    - (cd /tmp/libexif && autoreconf -sivf && ./configure --prefix=/tmp/libexif/install && make V=1 && make V=1 install)
  configure_script:
    - autoreconf -sivf
    - ./configure --prefix="${HOME}" CFLAGS="$CFLAGS" PKG_CONFIG_PATH="/tmp/libexif/install/lib/pkgconfig:/usr/libdata/pkgconfig:/usr/local/libdata/pkgconfig" POPT_CFLAGS="$(pkg-config --cflags popt)"  POPT_LIBS="$(pkg-config --libs popt)" || { tail -400 config.log; false; }
  compile_script:
    - make V=1
  test_script:
    - make V=1 check || { tail -400 test/test-suite.log; false; }
  install_script:
    - make V=1 install

linux_arm_task:
  name: ARM Linux
  arm_container:
    image: ubuntu:22.04
    memory: 350M

  env:
    # Set to 10 instead of 1 to avoid problems when new commits are submitted
    # during a run.
    CIRRUS_CLONE_DEPTH: 10
    CFLAGS: -Wall -Wextra -O2
    MAKE_FLAGS: -j 3

  pkginstall_script:
    - apt-get update -y && DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential autoconf automake autopoint libtool pkgconf git gettext libpopt-dev
    - git clone --depth=1 https://github.com/libexif/libexif.git /tmp/libexif
  builddeps_script:
    - (cd /tmp/libexif && autoreconf -sivf && ./configure --prefix=/tmp/libexif/install && make V=1 && make V=1 install)
  configure_script:
    - autoreconf -sivf
    - ./configure --prefix="${HOME}" CFLAGS="$CFLAGS" PKG_CONFIG_PATH="/tmp/libexif/install/lib/pkgconfig:/usr/libdata/pkgconfig:/usr/local/libdata/pkgconfig" || { tail -400 config.log; false; }
  compile_script:
    - make V=1
  test_script:
    - make V=1 check || { tail -400 test/test-suite.log; false; }
  install_script:
    - make V=1 install
