.\" © 2002 by Thomas Pircher (tehpeh at gmx dot net)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\" License.
.\" Modified 2002-09-08 by thomas
.\" Modified 2005-03-23 by hun
.\"
.TH exif 1 "2005-03-23" "" "libexif command line frontend"
.SH "NAME"
exif \- shows EXIF information in JPEG files
.SH "SYNOPSIS"
.BI "exif [ " "OPTION" " ] " "file"
.SH DESCRIPTION
.B "exif"
is a small command-line utility to show and change EXIF information in JPEG files.
.PP
Most digital cameras produce EXIF files, which are JPEG files with extra tags that contain information about the image. The
.B "exif"
command line utility allows you to read EXIF information from and write EXIF information to those files.
.PP
.B "exif"
internall uses the
.B "libexif"
library.
.SH "OPTIONS"
.TP
.BI "\-i, \-\-ids"
Show IDs instead of tag names
.TP
.BI "\-t, \-\-tag=" "tag"
Select
.I "tag"
.TP
.BI "\-\-ifd=" "IFD"
Select
.I "IFD"
.TP
.BI "\-l, \-\-list\-tags"
List all EXIF tags
.TP
.BI "\-|, \-\-show\-mnote"
Show contents of tag MakerNote
.TP
.BI "\-\-remove"
Remove tag or ifd
.TP
.BI "\-s, \-\-show\-description"
Show description of tag
.TP
.BI "\-e, \-\-extract\-thumbnail"
Extract thumbnail
.TP
.BI "\-r, \-\-remove\-thumbnail"
Remove thumbnail
.TP
.BI "-n, \-\-insert\-thumbnail=" "FILE"
Insert
.I "FILE"
as thumbnail
.TP
.BI "\-o, \-\-output=" "FILE"
Write output to
.I "FILE"
.TP
.BI "\-\-set\-value=" "VALUE"
Set value
.TP
.BI "\-m, \-\-machine\-readable"
Output in machine-readable (tab delimited) format
.SS "Help options"
.TP
.BI "\-?, \-\-help"
Show help message
.TP
.BI "\-\-usage"
Display brief usage message
.SH "AUTHOR"
Written by Lutz Mueller <lutz@users.sourceforge.net>
.SH "SEE ALSO"
.UR "http://www.sourceforge.net/projects/libexif"
.BR "http://www.sourceforge.net/projects/libexif"
